<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Thai Phan
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<ul class="address-validator-message">
    <li class="incorrect-address-title">Address could not be validated: </li>
    <li class="incorrect-address">Incorrect Address</li>
</ul>
<div class="address-validator-buttons">
    <input type="button" class="submit-button" id="submit-invalid-x-address" value="Continue Anyway" />
    <span class="cancel-link">or <a href="#" id="cancel-invalid-x-address">Edit address</a></span>
</div>
