<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Thai Phan
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<ul class="address-validator-message">
    <li class="provided-address"><span class="title">You entered:</span> <span class="address">Provided Address</span></li>
    <li class="validated-address"><span class="title">Did you mean:</span> <span class="address">Validated Address</span></li>
</ul>
<div class="address-validator-buttons">
    <input type="button" class="submit-button" id="submit-valid-x-address" value="Yes - use selected address" />
    <input type="button" class="submit-button" id="submit-user-x-address" value="No - use the address I entered" />
    <span class="cancel-link">or <a href="#" id="cancel-x-address">Edit address</a></span>
</div>
