<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Thai Phan
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::helper('australia/address')->isAddressValidationEnabled()): ?>
    <script>
        var addressValidationUrl = '<?php echo $this->getUrl('australia/address/validate') ?>';
        var australiaCountryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>;
        var addressSuggestTemplate = <?php echo json_encode($this->getChildHtml('fontis.australia.address.suggestion')) ?>;
        var addressFailureTemplate = <?php echo json_encode($this->getChildHtml('fontis.australia.address.failure')) ?>;
    </script>
    <script src="<?php echo $this->getSkinUrl('fontis/australia/js/opcheckout.js') ?>"></script>
<?php endif ?>
