<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Chris Norton
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $method = $this->getMethod(); ?>
<?php if($this->getParentBlock() && $this->getParentBlock()->getModuleName() == 'Mage_Checkout'): ?>
    <p><?php echo $method->getTitle() ?></p>
<?php else: ?>
    <?php $block = $this->getLayout()->createBlock('core/template'); ?>
    <?php $block->setTemplate('fontis/australia/payment/bpay/details.phtml'); ?>
    <?php $block->setBillerCode($method->getBillerCode()); ?>
    <?php $block->setRef($method->getRef()); ?>
    <?php echo $block->toHtml(); ?>
<?php endif; ?>
