<?php
/**
 * Fontis Australia Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @author     Chris Norton
 * @copyright  Copyright (c) 2014 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $method = $this->getMethod(); ?>
<dl id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list">
    <?php if ($method->getAccountName()): ?>
    <dt><?php echo $this->__('Account Name'); ?></dt>
    <dd><?php echo $method->getAccountName(); ?></dd>
    <?php endif;?>
    <?php if ($method->getAccountBSB()): ?>
    <dt><?php echo $this->__('Account BSB'); ?></dt>
    <dd><?php echo $method->getAccountBSB(); ?></dd>
    <?php endif;?>
    <?php if ($method->getAccountNumber()): ?>
    <dt><?php echo $this->__('Account Number'); ?></dt>
    <dd><?php echo $method->getAccountNumber(); ?></dd>
    <?php endif;?>
    <?php if ($method->getMessage()): ?>
    <dd><?php echo $method->getMessage(); ?></dd>
    <?php endif;?>
</dl>
